tsana_app_name: user
auto_data_retrieving: true
models_in_training_limit_per_instance: 1
az_tsana_meta_table: modelmeta
az_tsana_moniter_table: moniter
model_temp_dir: temp
model_dir: model
model_data_dir: data
training_owner_life: 60