apiVersion: v1
kind: Service
metadata:
  name: maga-plugin-loadbalancer
  namespace: maga-plugin
  labels:
    app: maga-plugin-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 52.148.149.151
  ports:
  - port: 56789
    protocol: TCP
    targetPort: 56789
  selector:
    app: maga-plugin
    role: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maga-plugin
  labels:
    app: maga-plugin
    role: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maga-plugin
      role: api
  template:
    metadata:
      labels:
        app: maga-plugin
        role: api
    spec:
      containers:
      - name: maga
        imagePullPolicy: Always
        image: tsanaplugin.azurecr.io/maga:20200701
        env:
        - name: TELEMETRY_TYPE
          value: "mon3"
        - name: MON3_SERVER
          value: "ks2-log-dev.westus2.cloudapp.azure.com:5201"
        - name: KENSHO2_PROFILE
          value: "maga-plugin"
        - name: MON3_APP
          value: "maga-plugin"
        - name: MON3_SERVICE
          value: "maga-plugin"
        - name: AZURE_STORAGE_ACCOUNT
          value: "tsana"
        - name: AZURE_STORAGE_ACCOUNT_KEY
          value: "<<AzureStorageAccountKey>>"
        ports:
        - containerPort: 56789
        livenessProbe:
          httpGet:
            path: /
            port: 56789
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
      imagePullSecrets:
      - name: tsanaplugin